### ISSUE TITLE
Ganon's tower regions not connected, logic puts lamp in armos knights chests

### ISSUE THREAD

**Issue by cryxia** [LLCoolDave/ALttPEntranceRandomizer#1]
See https://www.twitch.tv/videos/146196952?t=02h03m53s

Clearly lamp is in there! After looking through the code the location [dungeon-A2-B1] is tied to the region "Ganons Tower (Bottom)" - see https://github.com/LLCoolDave/ALttPEntranceRandomizer/blob/master/Regions.py#L247

However, "Ganon's Tower (Bottom)" isn't specified as a Location or Exit for another of the other regions in Ganon's Tower! From the randomiser's perspective, this region is detached, and thus reachable from the start of the game...

**Comment by cryxia** [comment]
Note that the only other exits that remotely resemble "Ganons Tower (Bottom)" are "Ganons Tower (Bottom) (West)" and "Ganons Tower (Bottom) (East)". The recursive lookup doesn't do a partial string match, so these three strings aren't treated as the same place.

**Comment by Matt14916** [comment]
Actually, it looks like https://github.com/LLCoolDave/ALttPEntranceRandomizer/blob/master/EntranceShuffle.py#L1127 and https://github.com/LLCoolDave/ALttPEntranceRandomizer/blob/master/EntranceShuffle.py#L1122 connect the bottom of ganon's tower, so this doesn't seem to be the ultimate issue.

**Comment by LLCoolDave** [comment]
Issue is in https://github.com/LLCoolDave/ALttPEntranceRandomizer/blob/master/Rules.py#335

world.state == 'open' should be world.mode == 'open'

So the lamp requirements due to open mode did not get added. As PoD, EP, MM and TR were all Light World in this seed, placing Lamp in GTower was considered valid. Fix will be included with other bug fixes today.

**Comment by cryxia** [comment]
Ah, fair enough. Guess my hunting was way off lol
